### ISSUE TITLE
Race condition between custom client and server

### ISSUE THREAD

**Issue by paolotron** [squillero/computational-intelligence#5]
When using a custom client that plays without user inputs, a race condition occurs if the client is too fast to play at the start of the game.
When all the players are ready, the game doesn't automatically start, instead a _ServerStartGameData_ packet is sent, this packet asks for a confirmation that the game can indeed start in the form of a _ClientPlayerReadyData_. No further feedback is given by the server after the response, the result is that the client assumes that he can start playing while it could be one of 3 cases:
1. All players correctly sent the answer and the game starts correctly
2. One or more player didn't send an answer and all the requests regarding the game are ignored
3. All players correctly sent an answer but the answers arrive after the first game requests and the former are ignored

This causes the server to ignore the majority of game requests at the start of the match if the clients are too fast.
This is further supported by the fact that by putting a sleep function after sending _ClientPlayerReadyData_ no further problems are detected and the match goes smoothly.
Curiously I think this stems from the famous [two general problem](https://en.wikipedia.org/wiki/Two_Generals%27_Problem)

**Comment by ThePseudo** [comment]
Fixed, thanks!
