### ISSUE TITLE
GameOver doesen't wait for players

### ISSUE THREAD

**Issue by paolotron** [squillero/computational-intelligence#6]
When the game terminates a _ServerGameOver_ packet is sent, then the server abruptly  stops, this means that the clients have a very small window to receive the message, if they can't receive it a _ConnectionResetError_ is lanched causing a crash on the client

**Comment by ThePseudo** [comment]
True. For now, this is not high priority, but I will surely look into it

**Comment by ThePseudo** [comment]
Solved with other issues
