### ISSUE TITLE
Starting game with 3 or more players impossible in automated system

### ISSUE THREAD

**Issue by paolotron** [squillero/computational-intelligence#7]
When using automated clients it's not possible to check for the number of connected players without sending a _ClientPlayerStartRequest_, this means that without arbitrary delays there cannot be synchronization between clients to determine the correct number of players.

**Comment by ThePseudo** [comment]
For now, you can pause for N seconds (maybe just 1) for every player to set the status to "ready". We will see if we will implement a server with fixed number of players.

**Comment by paolotron** [comment]
For high frequency training this solution is both ugly and unfeasable

**Comment by ThePseudo** [comment]
Solved, game automatically restarts
